name: Sync to venkatgroup Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          ORGANIZATION: kianpu34593
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_GITEE_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/dptech-corp/dflow.git"
          destination-repo: "git@gitee.com:deepmodeling/dflow.git"